In [7]:
import pandas as pd
df = pd.read_csv("gold_1m.csv")

In [8]:
df.head()

                        time     open     high      low    close  volume  rsi
0  2024-01-02 05:01:00+00:00  2062.14  2069.79  2062.14  2069.79       4  NaN
1  2024-01-02 05:02:00+00:00  2069.79  2069.79  2069.49  2069.53      66  NaN
2  2024-01-02 05:03:00+00:00  2069.53  2069.55  2069.39  2069.44      95  NaN
3  2024-01-02 05:04:00+00:00  2069.44  2069.67  2069.40  2069.64      93  NaN
4  2024-01-02 05:05:00+00:00  2069.64  2069.90  2069.56  2069.89      75  NaN

In [9]:
df = df[15:]
df.head()

,time,open,high,low,close,volume,rsi
15,2024-01-02 05:16:00+00:00,2071.46,2071.46,2071.05,2071.11,91,45.709571
16,2024-01-02 05:17:00+00:00,2071.11,2071.16,2070.75,2071.09,116,45.432474
17,2024-01-02 05:18:00+00:00,2071.09,2071.41,2071.09,2071.40,78,50.446804
18,2024-01-02 05:19:00+00:00,2071.40,2071.53,2070.91,2070.93,116,43.865360
19,2024-01-02 05:20:00+00:00,2070.93,2071.03,2070.75,2070.87,86,43.092454

In [ ]:
import numpy as np
import xgboost as xgb
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score